// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCELKSQbhH5LGVdJjeJmlrHaZAkIotXQQ0',
    appId: '1:24176289309:web:9f66031ffc73cf90b088f4',
    messagingSenderId: '24176289309',
    projectId: 'studentshub-265110',
    authDomain: 'studentshub-265110.firebaseapp.com',
    storageBucket: 'studentshub-265110.appspot.com',
    measurementId: 'G-PPEVVRSMK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSFNFwtaO9Jl9-qgAifK1JK4wQiPMnY4',
    appId: '1:24176289309:android:1d8c61d03e2097afb088f4',
    messagingSenderId: '24176289309',
    projectId: 'studentshub-265110',
    storageBucket: 'studentshub-265110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALVyT0ZVTMulwMC1IYsm7RBHs2Oak-z3A',
    appId: '1:24176289309:ios:ad165d83cd3c4e7db088f4',
    messagingSenderId: '24176289309',
    projectId: 'studentshub-265110',
    storageBucket: 'studentshub-265110.appspot.com',
    iosClientId: '24176289309-5aujc2es78mrigha9r19sr2sbh016p05.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebview',
  );
}
